import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { HeaderContantesTitle } from "./contants/headerContates";


import ClientHeader from "./components/ClientHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import 'animate.css';
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <header className='header'>

          <ClientHeader />

        </header>
        {children}
      </body>
    </html>
  );
}
